name: "Build & Publish Docker Image"
on:
  workflow_dispatch: {}
  push: {}

jobs:
  build:
    uses: "epimorphics/github-workflows/.github/workflows/build.yml@reusable"
    secrets:
      epi_gpr_access_token: "${{ secrets.EPI_GPR_ACCESS_TOKEN }}"
  publish:
    needs: "build"
    uses:  "epimorphics/github-workflows/.github/workflows/publish.yml@reusable"
    with:
      image:   "${{ needs.build.outputs.image }}"
      publish: "${{ needs.build.outputs.publish }}"
      tag:     "${{ needs.build.outputs.tag }}"
    secrets:
      aws_access_key_id:     "${{ secrets.BUILD_EPI_EXPT_AWS_ACCESS_KEY_ID }}"
      aws_secret_access_key: "${{ secrets.BUILD_EPI_EXPT_AWS_SECRET_ACCESS_KEY }}"
      epi_gpr_access_token:  "${{ secrets.EPI_GPR_ACCESS_TOKEN }}"
